language: node_js
node_js:
- '7.6'

branches:
  only:
    - master

before_script:
- npm install

script:
- npm run deploy

env:
  global:
    -secure: "vier00u+UUBc7I1ZjI/LjsK/e8V9myVaFsNbGRfk1+QejHkHxMTiCyW/zBDsJzTZCfbWnK5qTplVieObszVBqKZ8wZ6jYx4VCBr03iNEXl9DtrSuZUvzJSuAdhDLc07sp2Fmx0ykJxa3Go4vydYpYbjD2hvTeHVvmywtLnyCGTUWry5gjdth5D2lGlFOHn0wNabWqk1RMnn41sAw78bfM5vEAJ7Lrd3CmUNtRiLC0LzK2WM8cqQ2cJBPkL6dAqE4uIjvpjp72xjZ0yduUUAzZZkRzsMOmbh2DUHClEQn90tdWL3SfhbllSBoB4ZrUGwPngZn62d6BUiD91m6h4PIP9FOmPvJ4k/comSWFk0y1f712ZNgToeryGNRikPXC+Seh3dqb+SAwcm34AVHp3Q46F9iATnDjeXpb8AFnwW5hgoflDivQbV3kL3BF7hhOkAhSMBf5Efi06OHa1uzwTEJcX/SVbjE1cpYksRriNlVFleaP24ATQhUB11OqX/4064YQ6FxtmAlL1jqp345PkqwEXcUaC6aMSAiwuVpEcjVzt/YfQ+8M0cc7Be1VcdZExRMmADi4QK44KkK1ZzACscu/pj/edYbIhdeYfr/Gsi73EqaHIx38KvV7okBbZsLqU0G2ZAMp1pbbkvHkYmwwwb52jYyr87CwKhVHipQXbAkSDs="
